db:
  image: postgres

dataverse:
  restart: always
  build: dataverse
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - .:/code
  links:
    - db

glassfish:
  restart: always
  image: oracle/glassfish
  ports:
    - "8080:8080"
    - "8181:8181"
    - "4848:4848"
  volumes_from:
    - dataverse





nginx:
  restart: always
  build: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"


worker:
  image: vanessa/sregistry
  command: celery worker -A shub.celery -Q default -n default@%h -B
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
  links:
    - redis
    - db
